# Generated by Django 5.2.12 on 2026-03-17 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chaivarity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ML", "MASALA"),
                            ("GR", "GINGER"),
                            ("KL", "KIWI"),
                            ("PL", "PLAIN"),
                            ("EL", "ELAICHI"),
                        ],
                        default="PL",
                        max_length=2,
                    ),
                ),
                ("data_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
