# Generated by Django 5.2.12 on 2026-03-30 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "Description must be at least 10 characters."
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="chaivarity",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Chai name must be at least 2 characters."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        5, "Student age must be at least 5 years old."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "Please enter a valid age."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Student name must be at least 2 characters."
                    )
                ],
            ),
        ),
    ]
