# Generated by Django 5.2.12 on 2026-03-30 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_course_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="students.course"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "Description must be at least 10 characters."
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "Course title must be at least 3 characters."
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
